export function AboutPage() {
  return (
    <main className="flex flex-col grow mx-auto">
      <h2>About</h2>
      <div className="max-w-lg">
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam, pariatur. Blanditiis voluptatibus, porro eos ducimus suscipit praesentium quibusdam ratione corporis aut consectetur est, placeat laborum optio ullam deserunt, sapiente laboriosam.Aspernatur cumque explicabo ratione veritatis porro quas tempore error commodi pariatur itaque? Necessitatibus ipsa aliquid odit, dolore delectus dolorem, blanditiis atque molestias vitae corrupti provident impedit aliquam sequi explicabo cupiditate!Et non tenetur laborum. Dignissimos, hic incidunt? Placeat alias suscipit ipsam perspiciatis cumque nihil magni blanditiis? Provident, odio eius numquam voluptate cumque culpa, sint quam, voluptatibus iure repellat impedit officia!</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam quia quam ut excepturi corporis architecto, cupiditate illo eos mollitia deleniti non sapiente aspernatur molestias quod nam corrupti ea illum omnis.Perferendis voluptatem velit quasi accusantium? Expedita, soluta. Obcaecati voluptas ipsam ipsum nisi recusandae quasi suscipit asperiores facilis accusantium doloremque adipisci, quas atque architecto minima eum placeat magnam praesentium deserunt. Vitae!Aliquid, sed maiores quae qui recusandae alias praesentium magni esse suscipit! Perferendis asperiores possimus, ipsum, consectetur officia cum vitae facere molestias necessitatibus alias iusto earum. Aliquid cupiditate saepe voluptates illo?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis odio excepturi a quisquam unde delectus, nulla nesciunt soluta quod, distinctio, qui quaerat tenetur cumque ipsa. Modi incidunt id dignissimos necessitatibus!Minus velit rerum officiis consectetur, qui aspernatur dolores. Aspernatur corporis laudantium aliquam repudiandae, sequi at modi reprehenderit est minus similique. Quasi suscipit sed non hic! Officiis repellendus consequuntur veritatis provident?Dolor inventore libero quam vel nulla necessitatibus molestias mollitia perspiciatis, optio labore quisquam commodi, id molestiae fugiat quos tenetur! Quo facilis molestiae nesciunt laboriosam fugit, ea culpa in. Omnis, culpa!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Possimus corrupti libero aspernatur quaerat quisquam praesentium animi? Vero praesentium, quam doloribus adipisci reprehenderit minus voluptate aut accusantium impedit, ullam neque expedita.Quidem recusandae quo dolorem ullam magni vitae aliquam odio eos. Obcaecati quis delectus magnam, laudantium aut dolorem, qui fuga excepturi commodi perferendis a est exercitationem vitae odio dolorum aperiam dolor.Iusto aut modi rem dicta saepe dolor et, veniam facilis consectetur eaque repellendus non fuga totam cumque omnis consequuntur eveniet libero perferendis quo tempora voluptatibus iure molestiae. Eaque, atque. Voluptatem.</p>
      </div>
    </main>
  )
}